name             'ntp'
maintainer       'Rajesh Jonnalagadda'
maintainer_email 'vlnrajeshj@gmail.com'
license          'GPL v3'
description      'Installs/Configures ntp'
long_description 'Installs/Configures ntp'
version          '1.0.0'
depends          'firewalld'
supports         'centos', '7.1_1503'
supports	 'ubuntu', '14.04'
